### ISSUE TITLE
Video Aspect Aspect === Full in GameGear

### ISSUE THREAD

**Issue by d30r** [anzz1/DotUI-X#2]
changing between Aspect and Full produces no change. It appears as though "aspect" stretches out to cover the entire width of the screen.

**Comment by anzz1** [comment]
The Game Gear has a 4:3 aspect ratio, thus Aspect == Full in that case, just as you say. 
So that's not a bug, however this reminds me that earlier I did encounter a bug where changing between Aspect and Full sometimes needed a restart to get applied.

**Comment by d30r** [comment]
Thank you for the explanation ->issue closed
